### PR TITLE
Ignore scripting tags, speed improvement

### PR DESCRIPTION
**Pull request by bartbutler**
This PR does two things:

1. Ignore scripting tags like <?php
2. Improve iteration speed, especially for really large chunks of HTML text. Apparently iterating over DOMDocuments is very slow unless you do it in a specific way: https://stackoverflow.com/questions/13927221/how-to-improve-performance-iterating-a-domdocument

### CODE REVIEW

**Comment by bartbutler** [comment]
Also incorporated some code from #24 to better suppress warnings when $ignore_error = true, and propagate this preference to the fixMSEncoding function.

**Comment by soundasleep** [comment]
I like this MR, thank you! Can you add a test to check that scripting tags like <?php are ignored? And perhaps something to also check for the empty document fix?

**Comment by bartbutler** [comment]
Added, it turns out that the '<?php' case is covered internally somewhere. The crash happens when you use an unrecognized scripting tag like '<?a'. In any case, the tests are committed. I wasn't able to run them directly because the tests are incompatible with PHP 7 and upgrading them would have broken backwards compatibility, so I left them alone.

**Comment by soundasleep** [comment]
Travis runs the tests for us and they've passed so this MR looks great. Have merged. Thank you! :)

**Comment by bartbutler** [comment]
Thank you! This package is super-useful!

**Pull request merged**
