### PR TITLE
PHP8.x support

### PR DESCRIPTION
**Pull request by fglueck**
Optional Parameter before needed

### CODE REVIEW

**Comment by BenMorel** [comment]
This is already covered in #87, but it looks like [the project is dead](https://github.com/soundasleep/html2text/issues/89).

**Comment by fglueck** [comment]
thats true, sorry.

**Comment by soundasleep** [comment]
Hi everyone, I'm sorry there's not been a lot of action on this project recently! I don't have the time to support this project going forward so I'm looking for some maintainers 🙏 see: #91

**Comment by edgrosvenor** [comment]
Thank you! There were multiple PRs that did the same basic thing, so I chose this one to get it over the line: https://github.com/soundasleep/html2text/pull/87

**Pull request closed without merging**
