### PR TITLE
Mix Microsoft namespace and paragraph elements

### PR DESCRIPTION
**Pull request by thetaylor82**
Microsoft exchange emails often include HTML which is undocumented and non-standard. The <o:p> tags are handled as paragraphs by DOMDocument which results in huge amounts of line returns all mopped up by $output = preg_replace("/\n\n\n*/im", "\n\n", $output); that results in double line returns everywhere. To fix this the o:p elements should be removed and anything with a classname of MsoNormal (the standard classname in any Microsoft export or outlook for a paragraph that behaves like a line return) being changed to a line with a break afterwards. This makes emails display correctly while not impacting emails that do not have this encoding.

### CODE REVIEW

**Comment by soundasleep** [comment]
I love this change idea! Thank you so much for the PR. Is there any chance you can include a test file from MS Word so we can verify it works into the future?

**Comment by thetaylor82** [comment]
This is the source from an email I sent to test functionality:

`<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=us-ascii"><meta name=Generator content="Microsoft Word 15 (filtered medium)"><style></style></head><body lang=EN-GB link="#0563C1" vlink="#954F72"><div class=WordSection1><p class=MsoNormal>Dear html2text,<o:p></o:p></p><p class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal>This is an example email that can be used to test html2text conversion of outlook / exchange emails.<o:p></o:p></p><p class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal>The addition of &lt;o:p&gt; tags is very annoying!<o:p></o:p></p><p class=MsoNormal>This is a single line return<o:p></o:p></p><p class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal><b>This is bold<o:p></o:p></b></p><p class=MsoNormal><i>This is italic<o:p></o:p></i></p><p class=MsoNormal><u>This is underline<o:p></o:p></u></p><p class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal>Andrew<o:p></o:p></p></div></body></html>`

**Comment by soundasleep** [comment]
Thank you! I've put that into a new test file, added some more checks and code comments and this is now part of 0.3.4 - does this change work for you?

**Comment by thetaylor82** [comment]
Tested and confirmed working. Thank you very much!

**Pull request merged**
