### PR TITLE
Php 8.2 Support

### PR DESCRIPTION
**Pull request by phpfui**
PHP 8.2 depreciated `mb_convert_encoding($html, "HTML-ENTITIES", "UTF-8");`  The solution was to correctly specify the character set when loading the DOM.  Unfortunately, that only works on PHP 8.1 and higher, probably due to some bug that was fixed.  So I detect PHP 8.0 and lower and use the previous logic.  Not pretty, but it works.

I also modernized the package with the following improvements:
- Dropped PHP support below 7.3 due to poor support for PHPUnit (preexisting issue actually)
- Added parameter and return types for PHP 7.1 and higher
- Deleted composer.lock file and updated .gitignore to modern standards
- Updated unit tests to use data provider and separated out test files in to dedicated directories
- Updated actions to latest versions to avoid depreciations (one still left)
- I made the internal methods private as they should not be called directly
- I added a new option `char_set` to allow people to use a specific character set if known
- `char_set` option defaults to auto detect
- Updated README.md for `char_set` option

ToDo:
- Fix depreciation in test.yml but will leave that to someone else

### CODE REVIEW

**Comment by edgrosvenor** [comment]
@phpfui Thank you! This looks great. I'll get this merged in and get a release out over the holiday break.

**Comment by phpfui** [comment]
Ed,

Hope you had a good XMas weekend.  Any chance you could merge and publish a release?  I have three PR's for 8.2 compatibility.  One merged, two to go, and you can make it one to go!

This is a well thought out package and would love to see it continue.

Thanks.

**Comment by phpfui** [comment]
@edgrosvenor any chance we can get this merged and a new release published?  The PR looks like a lot of changes, but most are just housekeeping / cleanup. Let me know if you have any questions / issues.

**Comment by edgrosvenor** [comment]
@phpfui All set. Thank you!

**Pull request merged**
