### PR TITLE
Separate DOM parsing and conversion

### PR DESCRIPTION
**Pull request by valentinbonneaud**
This PR split the `convert` function into two public sub-functions `getDom` and `convertDOM`. This change allows you to easily have access to the parsed Dom object outside of the library. Furthermore, the function `convertDOM` use a new parameter to clone the DOM before it processes it as the conversion will remove the nodes of the DOM object.

### CODE REVIEW

**Comment by soundasleep** [comment]
Hello, thank you for your contribution!

I'm curious as to some of the background of this change. If you wanted access to the DOM of the source, could you not directly use `\DOMDocument#loadHTML` and load your own DOM instance?

Or, is it that you're looking to get html2text to convert an already-loaded `\DOMDocument` through `#convertDOM()`?

**Comment by valentinbonneaud** [comment]
Hi,

Thanks for your comment! Indeed, we already have the dom object loaded and we need to convert it using your `#convertDOM()` without reloading the dom object.

**Comment by BafS** [comment]
Any new about this PR @soundasleep ?

**Comment by bartbutler** [comment]
Superseded by #81

**Pull request closed without merging**
